export type TranscriptCue = { start: number; duration: number; text: string };
export type VideoMetadata = { title: string; author: string; description: string; transcript: TranscriptCue[]; chapters: { title: string; start: number }[] };
export type Clip = { title: string; hook: string; viralityScore: number; summary: string; startTime: number; endTime: number; videoId?: string };
const ID = '[a-zA-Z0-9_-]{11}'; const ID_RE = new RegExp(`^${ID}$`);
export function getYouTubeId(value: string) { const decoded = decodeURIComponent(value.trim()); if (ID_RE.test(decoded)) return decoded; try { const url = new URL(decoded.includes('://') ? decoded : `https://${decoded}`); const id = url.searchParams.get('v') || url.pathname.match(new RegExp(`/(?:shorts|embed|live|v)/(${ID})`))?.[1] || ''; return ID_RE.test(id) ? id : ''; } catch { return ''; } }
async function json(url: string) { const r = await fetch(url, { signal: AbortSignal.timeout(9000) }); if (!r.ok) throw new Error('unavailable'); return r.json(); }
function parseTranscript(data: any): TranscriptCue[] { const items = data?.transcript || data?.captions || data?.events || data; if (!Array.isArray(items)) return []; return items.map((x: any) => ({ start: Number(x.start ?? x.startTime ?? x.tStartMs / 1000 ?? 0), duration: Number(x.duration ?? x.dDurationMs / 1000 ?? 2), text: String(x.text ?? x.snippet?.text ?? x.segments?.map((s: any) => s.utf8).join('') ?? '').replace(/<[^>]+>/g, ' ').trim() })).filter(x => x.text && Number.isFinite(x.start)); }
async function fetchTranscript(id: string): Promise<TranscriptCue[]> { const urls = [`https://yt-subtitles.vercel.app/api?video_id=${id}`, `https://youtubetranscript.com/?server_vid2=${id}`, `https://api.allorigins.win/raw?url=${encodeURIComponent(`https://www.youtube.com/api/timedtext?v=${id}&lang=en&fmt=json3`)}`]; for (const url of urls) { try { const cues = parseTranscript(await json(url)); if (cues.length) return cues; } catch {} } return []; }
function extractChapters(description: string) { return description.split('\n').map(line => { const m = line.match(/(?:^|\s)(\d{1,2}:\d{2}(?::\d{2})?)\s+(.+)/); if (!m) return null; const p = m[1].split(':').map(Number); return { start: p.length === 3 ? p[0] * 3600 + p[1] * 60 + p[2] : p[0] * 60 + p[1], title: m[2].trim() }; }).filter(Boolean) as { title: string; start: number }[]; }
export async function fetchMetadata(id: string): Promise<VideoMetadata> { const url = `https://www.youtube.com/watch?v=${id}`; const results = await Promise.allSettled([json(`https://noembed.com/embed?url=${encodeURIComponent(url)}`), json(`https://www.youtube.com/oembed?url=${encodeURIComponent(url)}&format=json`)]); const data = results.map(r => r.status === 'fulfilled' ? r.value : null).find(x => x?.title); if (!data) throw new Error('Video not found or unavailable. Please check the YouTube URL.'); const transcript = await fetchTranscript(id); const description = String(data.description || '').trim(); return { title: data.title.trim(), author: String(data.author_name || data.author || 'Unknown channel').trim(), description, transcript, chapters: extractChapters(description) }; }
export function dynamicFallback(meta: VideoMetadata): Clip[] { const subject = meta.title.replace(/\s+/g, ' ').trim(); const cue = meta.transcript[0]?.text || meta.chapters[0]?.title || meta.description; const detail = cue ? `The available source text says: “${cue.slice(0, 180)}”` : 'No transcript or rich description was available, so the exact on-screen action could not be verified.'; return Array.from({ length: 5 }, (_, i) => { const start = meta.chapters[i]?.start ?? 30 + i * 150; return { title: `${subject} — source evidence unavailable`, hook: 'Needs transcript or visual review before publishing', summary: detail, viralityScore: 40, startTime: start, endTime: start + 42 }; }); }
export function parseClips(raw: string): Clip[] | null { try { const parsed = JSON.parse(raw.match(/\[[\s\S]*\]/)?.[0] || raw); if (!Array.isArray(parsed) || parsed.length < 5) return null; const clips = parsed.slice(0, 5).map((x: any, i) => ({ title: String(x.title || '').trim(), hook: String(x.hook || '').trim(), summary: String(x.summary || x.description || '').trim(), viralityScore: Math.max(0, Math.min(100, Number(x.viralityScore ?? x.virality_score) || 0)), startTime: Math.max(0, Number(x.startTime ?? x.start_time) || i * 60), endTime: Number(x.endTime ?? x.end_time) || 42 + i * 60 })); const unique = new Set(clips.map(c => `${c.title}|${c.startTime}|${c.endTime}`)); return unique.size === 5 && clips.every(c => c.title && c.hook && c.summary && c.endTime > c.startTime) ? clips : null; } catch { return null; } }
