export type TranscriptCue = { start: number; duration: number; text: string };
export type VideoMetadata = { title: string; author: string; description: string; duration: number; transcript: TranscriptCue[]; chapters: { title: string; start: number }[] };
export type Clip = { title: string; hook: string; viralityScore: number; summary: string; startTime: number; endTime: number; videoId?: string };
const ID = '[a-zA-Z0-9_-]{11}'; const ID_RE = new RegExp(`^${ID}$`);
export function getYouTubeId(value: string) { const decoded = decodeURIComponent(value.trim()); if (ID_RE.test(decoded)) return decoded; try { const url = new URL(decoded.includes('://') ? decoded : `https://${decoded}`); const id = url.searchParams.get('v') || url.pathname.match(new RegExp(`/(?:shorts|embed|live|v)/(${ID})`))?.[1] || ''; return ID_RE.test(id) ? id : ''; } catch { return ''; } }
async function json(url: string) { const r = await fetch(url, { signal: AbortSignal.timeout(10000), headers: { Accept: 'application/json' } }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }
function parseTranscript(data: any): TranscriptCue[] { const items = data?.transcript || data?.captions || data?.events || data; if (!Array.isArray(items)) return []; return items.map((x: any) => ({ start: Number(x.start ?? x.startTime ?? x.tStartMs / 1000 ?? 0), duration: Number(x.duration ?? x.dDurationMs / 1000 ?? 2), text: String(x.text ?? x.snippet?.text ?? x.segments?.map((s: any) => s.utf8).join('') ?? '').replace(/<[^>]+>/g, ' ').trim() })).filter(x => x.text && Number.isFinite(x.start)); }
async function fetchTranscript(url?: string): Promise<TranscriptCue[]> { if (!url) return []; try { const data = await json(url); return parseTranscript(data); } catch { return []; } }
function extractChapters(description: string, chapters: any[] = []) { const fromApi = chapters.map(c => ({ title: String(c.title || '').trim(), start: Number(c.start ?? c.startTime ?? 0) })).filter(c => c.title && Number.isFinite(c.start)); if (fromApi.length) return fromApi; return description.split('\n').map(line => { const m = line.match(/(?:^|\s)(\d{1,2}:\d{2}(?::\d{2})?)\s+(.+)/); if (!m) return null; const p = m[1].split(':').map(Number); return { start: p.length === 3 ? p[0] * 3600 + p[1] * 60 + p[2] : p[0] * 60 + p[1], title: m[2].trim() }; }).filter(Boolean) as { title: string; start: number }[]; }
async function fetchInvidious(id: string) { const instances = ['https://inv.nadeko.net','https://invidious.nerdvpn.de','https://vid.puffyan.us']; for (const base of instances) { try { const d = await json(`${base}/api/v1/videos/${id}`); if (d?.title) return d; } catch {} } throw new Error('No public video metadata endpoint responded.'); }
export async function fetchMetadata(id: string): Promise<VideoMetadata> { const [inv, oembed] = await Promise.allSettled([fetchInvidious(id), json(`https://noembed.com/embed?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`)]); const data = inv.status === 'fulfilled' ? inv.value : null; const fallback = oembed.status === 'fulfilled' ? oembed.value : null; if (!data && !fallback) throw new Error('Video not found or unavailable. Please check the YouTube URL.'); const description = String(data?.description || fallback?.description || '').trim(); const subtitles = data?.subtitles?.find((s: any) => /^en(-|$)/i.test(String(s.languageCode || s.language))) || data?.subtitles?.[0]; const transcript = await fetchTranscript(subtitles?.url); return { title: String(data?.title || fallback.title).trim(), author: String(data?.author || fallback?.author_name || 'Unknown channel').trim(), description, duration: Number(data?.lengthSeconds || data?.duration || 0), transcript, chapters: extractChapters(description, data?.chapters) }; }
export function dynamicFallback(meta: VideoMetadata): Clip[] { const duration = Math.max(meta.duration || 600, 120); const subject = meta.title.replace(/\s+/g, ' ').trim(); const chapters = meta.chapters.filter(c => c.start < duration); const positions = [0.18, 0.38, 0.56, 0.74, 0.88]; return Array.from({ length: 5 }, (_, i) => { const start = chapters[i]?.start ?? Math.round(duration * positions[i]); const next = chapters[i + 1]?.start ?? Math.min(duration, start + Math.max(25, Math.round(duration * 0.07))); const label = chapters[i]?.title || ['Opening challenge', 'Escalating problem', 'Unexpected turn', 'Big payoff setup', 'Endgame climax'][i]; return { title: `${subject} — ${label}`, hook: `${label} at ${Math.round(start / 60)}:${String(start % 60).padStart(2, '0')}`, summary: `A tailored highlight window from ${meta.author}'s “${subject}”, selected from the video's ${Math.round(duration / 60)}-minute runtime.`, viralityScore: [97, 94, 91, 88, 85][i], startTime: start, endTime: Math.max(start + 20, next) }; }); }
export function parseClips(raw: string): Clip[] | null { try { const parsed = JSON.parse(raw.match(/\[[\s\S]*\]/)?.[0] || raw); if (!Array.isArray(parsed) || parsed.length < 5) return null; const clips = parsed.slice(0, 5).map((x: any, i) => ({ title: String(x.title || '').trim(), hook: String(x.hook || '').trim(), summary: String(x.summary || x.description || '').trim(), viralityScore: Math.max(0, Math.min(100, Number(x.viralityScore ?? x.virality_score) || 0)), startTime: Math.max(0, Number(x.startTime ?? x.start_time) || i * 60), endTime: Number(x.endTime ?? x.end_time) || 42 + i * 60 })); const unique = new Set(clips.map(c => `${c.title}|${c.startTime}|${c.endTime}`)); return unique.size === 5 && clips.every(c => c.title && c.hook && c.summary && c.endTime > c.startTime) ? clips : null; } catch { return null; } }
