import { useState } from 'react';
import { Loader2, Play } from 'lucide-react';
import { analyzeVideo } from './lib/pollinations';
import { Clip, fetchMetadata, getYouTubeId } from './lib/analyze';

const stamp = (n: number) => { const s = Math.max(0, Math.round(n)); return `${String(Math.floor(s / 3600)).padStart(2, '0')}:${String(Math.floor(s / 60) % 60).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`; };
export default function App() {
  const [url, setUrl] = useState(''); const [clips, setClips] = useState<Clip[]>([]); const [selected, setSelected] = useState<Clip | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [videoId, setVideoId] = useState('');
  async function load() {
    setClips([]); setSelected(null); setMessage(''); const id = getYouTubeId(url);
    if (!id) { setMessage('Video not found or unavailable. Please check the YouTube URL.'); return; }
    setBusy(true); setMessage('Verifying video metadata...');
    try { const meta = await fetchMetadata(id); setMessage(`Analyzing “${meta.title}” by ${meta.author}...`); const result = (await analyzeVideo(meta)).map(c => ({ ...c, videoId: id })); setVideoId(id); setClips(result); setSelected(result[0] || null); setMessage(`Generated ${result.length} clips for “${meta.title}”.`); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Video not found or unavailable. Please check the YouTube URL.'); }
    finally { setBusy(false); }
  }
  const active = selected; const embed = active && videoId ? `https://www.youtube.com/embed/${videoId}?start=${Math.floor(active.startTime)}&autoplay=1&rel=0` : '';
  return <main className="min-h-screen grid-bg"><div className="max-w-6xl mx-auto p-4 sm:p-8"><header className="mb-8"><b className="text-2xl">CLIP<span className="text-emerald-400">FORGE</span></b><h1 className="text-4xl sm:text-5xl font-bold mt-8">Long-form in. <span className="text-emerald-400">Viral shorts out.</span></h1></header><section className="glass rounded-3xl p-5 sm:p-8"><div className="flex flex-col sm:flex-row gap-3"><input value={url} onChange={e => setUrl(e.target.value)} onKeyDown={e => e.key === 'Enter' && load()} placeholder="YouTube URL" className="flex-1 bg-zinc-950 border border-zinc-700 rounded-xl px-4 py-4 outline-none" /><button onClick={load} disabled={busy} className="bg-white text-black rounded-xl px-6 py-3 font-semibold flex justify-center">{busy ? <Loader2 className="animate-spin" /> : 'Analyze'}</button></div><p className="text-amber-300 mt-4 min-h-6">{message}</p></section>{clips.length > 0 && <section className="mt-6 grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6"><div><h2 className="font-bold text-xl mb-3">Viral moments <span className="text-emerald-400">{clips.length}</span></h2><div className="space-y-3">{clips.map((clip, i) => <button key={`${clip.startTime}-${i}`} onClick={() => setSelected(clip)} className={`glass rounded-xl p-4 w-full text-left ${selected === clip ? 'border-emerald-400 ring-1 ring-emerald-400' : ''}`}><div className="flex gap-3"><Play className="text-emerald-400 mt-1" size={18} fill="currentColor" /><div><div className="text-xs text-emerald-400">0{i + 1} · {stamp(clip.startTime)}–{stamp(clip.endTime)} · {clip.viralityScore}% VIRAL</div><h3 className="font-bold mt-2">{clip.title}</h3><p className="text-zinc-400 mt-1">{clip.hook}</p><p className="text-zinc-500 text-sm mt-2">{clip.summary}</p></div></div></button>)}</div></div>{active && <aside className="glass rounded-2xl p-4 lg:sticky lg:top-5"><div className="aspect-[9/16] bg-black rounded-xl overflow-hidden"><iframe title={active.title} src={embed} className="w-full h-full" allow="autoplay; encrypted-media" allowFullScreen /></div><h2 className="font-bold text-xl mt-4">{active.title}</h2><p className="text-zinc-400 mt-2">{active.summary}</p></aside>}</section>}</div></main>;
}
